### ISSUE TITLE
make the project pip installable

### ISSUE THREAD

**Issue by epapbak** [lucemia/doT#2]
Hi @lucemia,

It would be nice if this could be installed using pip. If it's OK with you, I can add the required files and even publish it to pip.

What do you think?

**Comment by lucemia** [comment]
Thanks, 
I will work on that tonight after my kids sleep.

**Comment by lucemia** [comment]
@epapbak 
The package is published https://pypi.org/project/dot-js-py/

If there is anything missing, issues or PR are more than welcome.

**Comment by epapbak** [comment]
Thanks!
